"""Render the Markdown report as a self-contained, styled HTML document.

The Markdown report from ``build_report`` is the source of truth; this converts it to a
standalone HTML page with inline CSS so it can be opened in a browser or handed to the PDF
renderer. Pure and deterministic given the Markdown input.
"""
from __future__ import annotations

_CSS = """
:root { color-scheme: light; }
* { box-sizing: border-box; }
body { font: 15px/1.6 -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
       color: #1a2233; background: #fff; margin: 0; }
.wrap { max-width: 900px; margin: 0 auto; padding: 40px 32px 64px; }
h1 { font-size: 26px; margin: 0 0 4px; color: #0f172a; }
h2 { font-size: 19px; margin: 32px 0 10px; padding-bottom: 6px; border-bottom: 2px solid #e2e8f0; color: #0f172a; }
h3 { font-size: 15px; margin: 20px 0 6px; color: #334155; text-transform: capitalize; }
p, li { margin: 4px 0; }
ul { padding-left: 22px; }
code { background: #f1f5f9; padding: 1px 5px; border-radius: 4px; font: 13px/1.5 ui-monospace, Menlo, Consolas, monospace; }
pre { background: #0f172a; color: #e2e8f0; padding: 14px; border-radius: 8px; overflow-x: auto; }
pre code { background: none; color: inherit; padding: 0; }
table { border-collapse: collapse; width: 100%; margin: 10px 0; }
th, td { border: 1px solid #e2e8f0; padding: 6px 10px; text-align: left; font-size: 13px; }
th { background: #f8fafc; }
em { color: #64748b; font-style: normal; font-size: 13px; }
strong { color: #0f172a; }
/* Risk & exposure gets a red left rail via its emphasis markers */
h2 + p + ul li strong { color: inherit; }
.risk { border-left: 4px solid #dc2626; background: #fef2f2; padding: 2px 12px; border-radius: 6px; }
a { color: #2563eb; text-decoration: none; word-break: break-all; }
footer { margin-top: 40px; padding-top: 12px; border-top: 1px solid #e2e8f0; color: #94a3b8; font-size: 12px; }
@media print { .wrap { max-width: none; padding: 0; } h2 { break-after: avoid; } li { break-inside: avoid; } }
"""


def markdown_to_html(md_text: str) -> str:
    """Convert Markdown body to an HTML fragment (tables + fenced code)."""
    import markdown  # imported lazily so the core report has no hard dep
    return markdown.markdown(md_text, extensions=["tables", "fenced_code", "sane_lists"])


def build_html_report(md_text: str, *, title: str = "Weft OSINT report") -> str:
    """Wrap the converted Markdown in a full, self-contained HTML document."""
    body = markdown_to_html(md_text)
    # give the Risk & exposure list a visual rail
    body = body.replace("<h2>Risk &amp; exposure</h2>", '<h2 id="risk">Risk &amp; exposure</h2>')
    return (
        "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\">"
        f"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>{_escape(title)}</title>"
        f"<style>{_CSS}</style></head><body><div class=\"wrap\">{body}"
        "<footer>Generated by Weft — free-source OSINT reconnaissance. Public sources only; "
        "each finding records its provenance and confidence.</footer>"
        "</div></body></html>"
    )


def _escape(s: str) -> str:
    return (s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))
